ISU By DBugSolutions/Models/CreateRole.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ISU_By_DBugSolutions.Models
{
    public class CreateRole
    {
        [Required]
        [DisplayName("Role Name")]
        public string RoleName { get; set; }
    }
}

ISU By DBugSolutions/Models/EditRole.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ISU_By_DBugSolutions.Models
{
    public class EditRole
    {
        public EditRole()
        {
            Users = new List<string>();
        }
        public string Id { get; set; }
        [Required(ErrorMessage = "Role Name is Required")]
        public string RoleName { get; set; }
        public List<string> Users { get; set; }
    }
}

ISU By DBugSolutions/Models/EditUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ISU_By_DBugSolutions.Models
{
    public class EditUser
    {
        public string Id { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public string UserName { get; set; }
        public List<string> Claims { get; set; }
        public IList<string> Roles { get; set; }

        public EditUser()
        {
            Claims = new List<string>();
            Roles = new List<string>();
        }
    }
}

ISU By DBugSolutions/Controllers/AdministrationController.cs
using ISU_By_DBugSolutions.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.VisualStudio.Services.DelegatedAuthorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ISU_By_DBugSolutions.Controllers
{
  
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ILogger<AdministrationController> logger;

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, ILogger<AdministrationController> logger)
        {
            this.logger = logger;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                var user = await userManager.FindByIdAsync(userId);

                if (user == null)
                {
                    ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found.";
                    return View("NotFound");
                }

                var existingUserClaims = await userManager.GetClaimsAsync(user);

                var model = new UserClaims { UserId = userId };

                foreach (Claim claim in ClaimsStore.AllClaims)
                {
                    UserClaim userClaim = new UserClaim { ClaimType = claim.Type };

                    if (existingUserClaims.Any(c => c.Type == claim.Type && (c.Value == "true")))
                    {
                        userClaim.IsSelected = true;
                    }
                    model.Claims.Add(userClaim);
                }

                return View(model);
            }
            else
            {
                return Error();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ManageUserClaims(UserClaims model)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                var user = await userManager.FindByIdAsync(model.UserId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {model.UserId} cannot be found.";
                return View("NotFound");
            }

            var claims = await userManager.GetClaimsAsync(user);
            var result = await userManager.RemoveClaimsAsync(user, claims);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing claims");
                return View(model);
            }

            result = await userManager.AddClaimsAsync(user, model.Claims.Select(c => new Claim(c.ClaimType, c.IsSelected ? "true" : "false")));

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected claims to user");
                return View(model);
            }

            return RedirectToAction("EditUser", new { Id = model.UserId });
            }
            else
            {
                return Error();
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View("ListUsers");
            }
            }
            else
            {
                return Error();
            }
        }
       
        [HttpGet]
        public IActionResult ListUsers()
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                var users = userManager.Users;

            return View(users);
            }
            else
            {
                return Error();
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }

            var userClaims = await userManager.GetClaimsAsync(user);
            var userRoles = await userManager.GetRolesAsync(user);

            var model = new EditUser
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.Email,
                Claims = userClaims.Select(c => c.Type + " : " + c.Value).ToList(),
                Roles = userRoles
            };
            return View(model);
            }
            else
            {
                return Error();
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUser model)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                var user = await userManager.FindByIdAsync(model.Id);

                if (user == null)
                {
                    ViewBag.ErrorMessage = $"User with Id = {model.Id} cannot be found";
                    return View("NotFound");
                }
                else
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await userManager.UpdateAsync(user);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListUsers");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    return View(model);
                }
            }
            else
            {
                return Error();
            }
            
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserRoles(string userId)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                ViewBag.userId = userId;

            var user = await userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoles>();

            foreach (var role in roleManager.Roles)
            {
                var userRoles = new UserRoles
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoles.IsSelected = true;
                }
                else
                {
                    userRoles.IsSelected = false;
                }

                model.Add(userRoles);
            }
            return View(model);
            }
            else
            {
                return Error();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ManageUserRoles(List<UserRoles> model, string userId)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                var user = await userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found.";
                return View("NotFound");
            }

            var roles = await userManager.GetRolesAsync(user);
            var result = await userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles.");
                return View(model);
            }

            result = await userManager.AddToRolesAsync(user, model.Where(x => x.IsSelected).Select(y => y.RoleName));

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add the selected roles to the user.");
                return View(model);
            }

            return RedirectToAction("EditUser", new { Id = userId });
            }
            else
            {
                return Error();
            }
        }

        //Role
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRole model)
        {
           
                if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole { Name = model.RoleName };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {

ISU By DBugSolutions/Views/Administration/AccessDenied.cshtml
<div class="text-center mt-2">

    <h1 class="text-danger">Access Denied</h1>
    <h6 class="text-danger">You do not have permission to view this resource</h6>
    <img class="mt-4" src="~/Images/error-icon.png" width="400"/>   
</div>

ISU By DBugSolutions/Views/Administration/CreateRole.cshtml
@model ISU_By_DBugSolutions.Models.CreateRole

@{
    ViewData["Title"] = "Create New Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add New Role</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Role" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<a asp-action="ListRoles"><img src="~/Images/back-icon.png" alt="back" style="width:35px;" class="mr-1" /></a>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ISU By DBugSolutions/Views/Administration/EditRole.cshtml
@model EditRole

@{
    ViewBag.Title = "Edit Role";
}
 
<div class="">
    <h1 class="">Edit Role</h1>
</div>
<hr />

<form class="mt-3" method="post">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label text-secondary"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label text-secondary"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>
   
    <div class="col-sm-10">
        <button type="submit" class="btn btn-submit-1">Update</button>
        <a asp-action="ListRoles" class="btn btn-submit-1">Cancel</a>
    </div>

    <div class="card">
        <div class="card-header">
            <h3 class="">Users in this role</h3>
        </div>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@Model.Id" class="btn btn-primary" style="width:auto">Add or Remove Users</a>
        </div>

    </div>

</form>

ISU By DBugSolutions/Views/Administration/EditUser.cshtml
@model EditUser

@{
    ViewBag.Title = "Edit User";
}

<h1 class="greyFont">Edit User</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-secondary"></span>
        </div>
    </div>

   

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="link002">Update</button>
            <a asp-action="ListUsers" class="btn btn-secondary">Cancel</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3 class="">User Roles</h3>
        </div>
        <div class="card-body">
            @if (Model.Roles.Any())
            {
                foreach (var role in Model.Roles)
                {
                    <h5 class="card-title">@role</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="ManageUserRoles" asp-route-userId="@Model.Id" style="width:auto" class="">Manage Roles</a>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-header">
            <h3 class="">User Claims</h3>
        </div>
        <div class="card-body">
            @if (Model.Claims.Any())
            {
                foreach (var claim in Model.Claims)
                {
                    <h5 class="card-title">@claim</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="ManageUserClaims" asp-route-userId="@Model.Id" style="width:auto" class="">Manage Claims</a>
        </div>
    </div>
</form>

ISU By DBugSolutions/Views/Administration/EditUsersInRole.cshtml
@model List<UserRole>

@{
    var roleId = ViewBag.roleId;
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2 class="">Add or remove Users from this Role</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check ">
                    <input type="hidden" asp-for="@Model[i].UserId" />
                    <input type="hidden" asp-for="@Model[i].UserName" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">@Model[i].UserName</label>
                </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-submit-1" style="width:auto" />
            <a asp-action="EditRole" asp-route-id="@roleId" class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

ISU By DBugSolutions/Views/Administration/ListRoles.cshtml
@model IEnumerable<IdentityRole>

@{
    ViewBag.Title = "All Roles";
}

<h1>Roles - List</h1>

@if (Model.Any())
{
    <a class="btn btn-primary" style="width:auto" asp-action="CreateRole" asp-controller="administration">Add new role</a>

    foreach (var role in Model)
    {
        <div class="card-mb-3">
            <div class="card-header">
                Role Id: @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <form asp-action="DeleteRole" asp-route-id="@role.Id" method="post">
                    <a asp-action="EditRole" asp-controller="Administration" asp-route-id="@role.Id" class="btn btn-primary">Edit</a>

                    <span id="confirmDeleteSpan_@role.Id" style="display:none">
                        <span>Are you sure you want to delete?</span>
                        <button type="submit">Yes</button>
                        <a href="#" onclick="confirmDelete('@role.Id',false)">No</a>
                    </span>
                    <span id="deleteSpan_@role.Id">
                        <a href="#" class="btn btn-danger" onclick="confirmDelete('@role.Id', true)">Delete</a>
                    </span>
                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            No roles Created yet
        </div>
        <div class="class-body">
            <h5 class="card-title">
                Use the button below to create a role
            </h5>
            <a style="width:auto" asp-controller="administration" asp-action="CreateRole">Create Role</a>
        </div>
    </div>
}
@section Scripts{ 
    <script src="~/js/CustomScript.js"></script>
}

ISU By DBugSolutions/Views/Administration/ListUsers.cshtml
@model IEnumerable<ApplicationUser>

@{
    ViewBag.Title = "All Users";
}

<h1 class="greyFont">All Users</h1>

@if (Model.Any())
{
    <a class="btn btn-primary" style="width:auto" asp-controller="Account" asp-action="Register">Add new user</a>

    foreach (var user in Model)
    {
        <div class="card mb-3">
            <div class="card-header">User Id: @user.Id</div>
            <div class="card-body">@user.FirstName</div>
            <div class="card-footer">
                <form asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                    <a asp-action="EditUser" asp-controller="Administration" asp-route-id="@user.Id" class="btn btn-primary">Edit</a>

                    <span id="confirmDeleteSpan_@user.Id" style="display:none">
                        <span>Are you sure you want to delete?</span>
                        <button type="submit" class="btn btn-danger">Yes</button>
                        <a href="#" class="" onclick="confirmDelete('@user.Id',false)">No</a>
                    </span>
                    <span id="deleteSpan_@user.Id">
                        <a href="#" class="" onclick="confirmDelete('@user.Id', true)">Delete</a>
                    </span>

                </form>
            </div>
        </div>

    }
}
else
{
    <div class="card">
        <div class="card-header">No Users Created yet</div>
        <div class="card-body">
            <h5 class="card-title greyFont">Use the button below to create a user</h5>
            <a class="link002" style="width:auto" asp-controller="Account" asp-action="Register">Add</a>
        </div>
    </div>

}

@section Scripts
{
    <script src="~/js/CustomScript.js"></script>
}

ISU By DBugSolutions/Views/Administration/ManageUserClaims.cshtml
@model UserClaims

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2 class="">Manage User Claims</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Claims.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model.Claims[i].ClaimType" />
                    <input asp-for="@Model.Claims[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model.Claims[i].IsSelected">@Model.Claims[i].ClaimType</label>

                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-submit-1" style="width:auto" />
            <a asp-action="EditUser" asp-route-id="@Model.UserId" class="btn btn-submit-1" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

ISU By DBugSolutions/Views/Administration/ManageUserRoles.cshtml
@model List<UserRoles>

@{
    var userId = ViewBag.userId;
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2 class="">Manage User Roles</h2>
        </div>
        <div class="card-body">

            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].RoleId" />
                    <input type="hidden" asp-for="@Model[i].RoleName" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">@Model[i].RoleName</label>
                </div>
            }
       
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="" style="width:auto" />
            <a asp-action="EditUser" asp-route-id="@userId" class="btn btn-secondary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>