ISU By DBugSolutions/Models/MedicalHistory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ISU_By_DBugSolutions.Models
{
    public class MedicalHistory
    {
        [Key]
        public int MedHistID { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string PupilName { get; set; }
        [Required]
        [Display(Name = "Surname")]
        public string PupilSurname { get; set; }
        [Required]
        [Display(Name = "Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Date { get; set; }
     
        [Display(Name = "Disease")]
        public string DiseaseName { get; set; }
        public IEnumerable<Disease> _DiseaseName{ get; set; }
    
        [Display(Name = "Surgery")]
        public string SurgeryName { get; set; }
        public IEnumerable<Surgery> _SurgeryName { get; set; }
    
        [Display(Name = "Allergy")]
        public string AllergyName { get; set; }
        public IEnumerable<Allergy> _AllergyName { get; set; }
    
        [Display(Name = "Doctor")]
        public string DoctorName { get; set; }
        public IEnumerable<Doctor> _DoctorName { get; set; }
      
        [Display(Name = "Medication")]
        public string MedicationName { get; set; }
        public IEnumerable<Medication> _MedicationName { get; set; }
        public string SearchTerm { get; set; }
    }
}

ISU By DBugSolutions/Controllers/MedicalHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ISU_By_DBugSolutions.Models;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Grid;
using Syncfusion.Pdf;
using Syncfusion.Drawing;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace ISU_By_DBugSolutions.Controllers
{
    [Authorize(Roles = "Admin, ECDC Manager, Teacher")]
    public class MedicalHistoryController : Controller
    {
        private readonly ApplicationDBContext _context;

        public MedicalHistoryController(ApplicationDBContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Admin, ECDC Manager, Teacher, Parent")]
        // GET: MedicalHistory
        public IActionResult Index(int pg = 1, string SearchText = "")
        {
            List<MedicalHistory> enq = _context.MedicalHistory.ToList();
            if (SearchText != "" && SearchText != null)
            {
                enq = _context.MedicalHistory.Where(p => p.PupilName.Contains(SearchText) || p.AllergyName.Contains(SearchText) 
                                                        || p.DiseaseName.Contains(SearchText) || p.DoctorName.Contains(SearchText) 
                                                        || p.MedicationName.Contains(SearchText) || p.PupilSurname.Contains(SearchText)
                                                        || p.SurgeryName.Contains(SearchText)).ToList();


            }
            else
            {
                enq = _context.MedicalHistory.ToList();
            }

            const int pageSize = 5;
            if (pg < 1)
            {
                pg = 1;
            }
            int recsCount = enq.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = enq.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            return View(data);
        }

        // GET: MedicalHistory/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicalHistory = await _context.MedicalHistory.FirstOrDefaultAsync(m => m.MedHistID == id);
            if (medicalHistory == null)
            {
                return NotFound();
            }

            return View(medicalHistory);
        }

        // GET: MedicalHistory/Create
        public IActionResult Create()
        {
            List<Pupil> listPupil = new List<Pupil>();
            listPupil = (from pup in _context.Pupil select pup).ToList();
            ViewBag.listOfPupils = listPupil;

            List<Disease> listDisease = new List<Disease>();
            listDisease = (from Dis in _context.Disease select Dis).ToList();
            ViewBag.listOfDiseases = listDisease;

            List<Surgery> listSurgery = new List<Surgery>();
            listSurgery = (from Sur in _context.Surgery select Sur).ToList();
            ViewBag.listOfSurgeries = listSurgery;

            List<Allergy> listAllergy = new List<Allergy>();
            listAllergy = (from All in _context.Allergy select All).ToList();
            ViewBag.listOfAllergies = listAllergy;

            List<Doctor> listDoctor = new List<Doctor>();
            listDoctor = (from Doc in _context.Doctor select Doc).ToList();
            ViewBag.listOfDoctors = listDoctor;

            List<Medication> listMed = new List<Medication>();
            listMed = (from Med in _context.Medication select Med).ToList();
            ViewBag.listOfMedications = listMed;

            return View();
        }

        // POST: MedicalHistory/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MedHistID,PupilName,PupilSurname,Date,DiseaseName,SurgeryName,AllergyName,DoctorName,MedicationName")] MedicalHistory medicalHistory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicalHistory);
                await _context.SaveChangesAsync();
                TempData["Message"] = "success";
                return RedirectToAction(nameof(Index));
            }
            return View(medicalHistory);
        }

        // GET: MedicalHistory/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            List<Pupil> listPupil = new List<Pupil>();
            listPupil = (from pup in _context.Pupil select pup).ToList();
            ViewBag.listOfPupils = listPupil;

            List<Disease> listDisease = new List<Disease>();
            listDisease = (from Dis in _context.Disease select Dis).ToList();
            ViewBag.listOfDiseases = listDisease;

            List<Surgery> listSurgery = new List<Surgery>();
            listSurgery = (from Sur in _context.Surgery select Sur).ToList();
            ViewBag.listOfSurgeries = listSurgery;

            List<Allergy> listAllergy = new List<Allergy>();
            listAllergy = (from All in _context.Allergy select All).ToList();
            ViewBag.listOfAllergies = listAllergy;

            List<Doctor> listDoctor = new List<Doctor>();
            listDoctor = (from Doc in _context.Doctor select Doc).ToList();
            ViewBag.listOfDoctors = listDoctor;

            List<Medication> listMed = new List<Medication>();
            listMed = (from Med in _context.Medication select Med).ToList();
            ViewBag.listOfMedications = listMed;

            if (id == null)
            {
                return NotFound();
            }

            var medicalHistory = await _context.MedicalHistory.FindAsync(id);
            if (medicalHistory == null)
            {
                return NotFound();
            }
            return View(medicalHistory);
        }

        // POST: MedicalHistory/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MedHistID,PupilName,PupilSurname,Date,DiseaseName,SurgeryName,AllergyName,DoctorName,MedicationName")] MedicalHistory medicalHistory)
        {
            if (id != medicalHistory.MedHistID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicalHistory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicalHistoryExists(medicalHistory.MedHistID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicalHistory);
        }

        // GET: MedicalHistory/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicalHistory = await _context.MedicalHistory
                .FirstOrDefaultAsync(m => m.MedHistID == id);
            if (medicalHistory == null)
            {
                return NotFound();
            }

            return View(medicalHistory);
        }

        // POST: MedicalHistory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medicalHistory = await _context.MedicalHistory.FindAsync(id);
            _context.MedicalHistory.Remove(medicalHistory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicalHistoryExists(int id)
        {
            return _context.MedicalHistory.Any(e => e.MedHistID == id);
        }
        public IActionResult CreateDocument()
        {

            PdfDocument doc = new PdfDocument();

            PdfPage page = doc.Pages.Add();

            PdfGrid pdfGrid = new PdfGrid();

            List<MedicalHistory> enq = _context.MedicalHistory.ToList();


            IEnumerable<object> dataTable = enq;

            pdfGrid.DataSource = dataTable;

            PdfGraphics graphics = page.Graphics;


            PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 20);
            PdfFont font1 = new PdfStandardFont(PdfFontFamily.Helvetica, 13);
            graphics.DrawString("Student Medical History - Report:", font, PdfBrushes.Black, new PointF(0, 0));
            string date = DateTime.Now.ToString();
            graphics.DrawString(date, font1, PdfBrushes.Black, new PointF(350, 5));
            pdfGrid.Draw(page, new Syncfusion.Drawing.PointF(10, 50));

            MemoryStream stream = new MemoryStream();
            doc.Save(stream);

            stream.Position = 0;

            doc.Close(true);

            string contentType = "application/pdf";

            string fileName = "Report.pdf";

            return File(stream, contentType, fileName);
        }
    }
}

ISU By DBugSolutions/Views/MedicalHistory/Create.cshtml
@model ISU_By_DBugSolutions.Models.MedicalHistory

@{
    ViewData["Title"] = "Medical History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="mb-3" src="~/Images/med-hist-header.png" alt="Videos" width="300" />

<div class="alert alert-secondary alert-dismissible fade show" role="alert"> Complete form and submit to add medical history.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PupilName" class="control-label"></label>
                <select asp-for="PupilName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfPupils,"FirstName","FirstName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="PupilName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PupilSurname" class="control-label"></label>
                <select asp-for="PupilSurname" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfPupils,"LastName","LastName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="PupilSurname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" type="date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiseaseName" class="control-label"></label>
                <select asp-for="DiseaseName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfDiseases,"DiseaseName","DiseaseName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="DiseaseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SurgeryName" class="control-label"></label>
                <select asp-for="SurgeryName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfSurgeries,"SurgeryName","SurgeryName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="SurgeryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AllergyName" class="control-label"></label>
                <select asp-for="AllergyName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfAllergies,"AllergyName","AllergyName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="AllergyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorName" class="control-label"></label>
                <select asp-for="DoctorName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfDoctors,"FirstName","FirstName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="DoctorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicationName" class="control-label"></label>
                <select asp-for="MedicationName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfMedications,"MedicationName","MedicationName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="MedicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-submit-1" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ISU By DBugSolutions/Views/MedicalHistory/Delete.cshtml
@model ISU_By_DBugSolutions.Models.MedicalHistory

@{
    ViewData["Title"] = "Medical History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="mb-3" src="~/Images/med-hist-header.png" alt="Videos" width="300" />

<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Warning!</strong> Deleted records cannot be recovered<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>

<div>
    <h4>MedicalHistory</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PupilName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PupilName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PupilSurname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PupilSurname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiseaseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiseaseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SurgeryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SurgeryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AllergyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AllergyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DoctorName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MedicationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MedicationName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="MedHistID" />
        <a asp-action="Index"><img src="~/Images/back-icon.png" alt="back" style="width:35px;" class="mr-1" /></a>
        <input type="submit" value="Delete" class="btn btn-submit-1" />
    </form>
</div>

ISU By DBugSolutions/Views/MedicalHistory/Details.cshtml
@model ISU_By_DBugSolutions.Models.MedicalHistory

@{
    ViewData["Title"] = "Medical History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="mb-3" src="~/Images/med-hist-header.png" alt="Videos" width="300" />
<hr />
<div>
    <h4>MedicalHistory</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PupilName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PupilName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PupilSurname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PupilSurname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiseaseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiseaseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SurgeryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SurgeryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AllergyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AllergyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DoctorName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MedicationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MedicationName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index"><img src="~/Images/back-icon.png" alt="back" style="width:35px;" class="mr-1" /></a>

</div>

ISU By DBugSolutions/Views/MedicalHistory/Edit.cshtml
@model ISU_By_DBugSolutions.Models.MedicalHistory

@{
    ViewData["Title"] = "Medical History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="mb-3" src="~/Images/med-hist-header.png" alt="Videos" width="300" />

<h4><i>Edit details</i></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MedHistID" />
            <div class="form-group">
                <label asp-for="PupilName" class="control-label"></label>
                <select asp-for="PupilName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfPupils,"FirstName","FirstName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="PupilName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PupilSurname" class="control-label"></label>
                <select asp-for="PupilSurname" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfPupils,"LastName","LastName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="PupilSurname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiseaseName" class="control-label"></label>
                <select asp-for="DiseaseName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfDiseases,"DiseaseName","DiseaseName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="DiseaseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SurgeryName" class="control-label"></label>
                <select asp-for="SurgeryName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfSurgeries,"SurgeryName","SurgeryName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="SurgeryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AllergyName" class="control-label"></label>
                <select asp-for="AllergyName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfAllergies,"AllergyName","AllergyName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="AllergyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorName" class="control-label"></label>
                <select asp-for="DoctorName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfDoctors,"FirstName","FirstName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="DoctorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicationName" class="control-label"></label>
                <select asp-for="MedicationName" class="form-control" asp-items="@(new SelectList(@ViewBag.listOfMedications,"MedicationName","MedicationName"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="MedicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index"><img src="~/Images/back-icon.png" alt="back" style="width:35px;" class="mr-1" /></a>
                <input type="submit" value="Save" class="btn btn-submit-1" />

            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ISU By DBugSolutions/Views/MedicalHistory/Index.cshtml
@model IEnumerable<ISU_By_DBugSolutions.Models.MedicalHistory>

@{
    ViewData["Title"] = "Medical History";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Pager pager = new Pager();
    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
    int intSno = 0;
}

<img class="mb-3" src="~/Images/med-hist-header.png" alt="Videos" width="300" />
@if (TempData["Message"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert"> <strong>Success!</strong> Record Successfully added.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
}
<p class="h4">
    <a asp-action="Create" class="text-secondary"><i class="bx bxs-plus-square h1 shake"></i><span class="badge badge-secondary h1 bg-anim">Add New</span></a>
</p>
<hr />
<div class="col-4 p-0 justify-content-end">
    <form asp-controller="MedicalHistory" asp-action="Index" class="form-inline">
        <input class="form-control mr-sm-2" type="text" name="SearchText" placeholder="Search..." />
        <button class="btn btn-submit my-2 my-sm-0" type="submit" value="Search">
            Search
        </button>
    </form>
</div>
<table class="table">

    <tbody>
        @foreach (var item in Model)
        {
            intSno = intSno + 1;
            <tr>
                <td>
                    <div class="info-block-2 bg-dark">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-9 text-light pl-5">

                                    <h3 class="text-secondary">
                                        @Html.DisplayFor(modelItem => item.PupilName) &nbsp;
                                        @Html.DisplayFor(modelItem => item.PupilSurname)
                                    </h3>

                                    <p>
                                        @Html.DisplayNameFor(model => model.Date): &nbsp; @Html.DisplayFor(modelItem => item.Date)
                                    </p>

                                    <p>
                                        @Html.DisplayNameFor(model => model.DiseaseName): &nbsp; @Html.DisplayFor(modelItem => item.DiseaseName)
                                    </p>

                                    <p>
                                        @Html.DisplayNameFor(model => model.SurgeryName): &nbsp; @Html.DisplayFor(modelItem => item.SurgeryName)
                                    </p>
                                    <p>
                                        @Html.DisplayNameFor(model => model.AllergyName): &nbsp; @Html.DisplayFor(modelItem => item.AllergyName)
                                    </p>
                                    <p>
                                        @Html.DisplayNameFor(model => model.DoctorName): &nbsp; @Html.DisplayFor(modelItem => item.DoctorName)
                                    </p>
                                    <p>
                                        @Html.DisplayNameFor(model => model.MedicationName): &nbsp;@Html.DisplayFor(modelItem => item.MedicationName)
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MedHistID" class="text-primary h2"><i class='bx bxs-edit'></i></a>
                    <a asp-action="Details" asp-route-id="@item.MedHistID" class="text-secondary h2"><i class='bx bx-list-ul'></i></a>
                    <a asp-action="Delete" asp-route-id="@item.MedHistID" class="text-danger h2"><i class='bx bx-trash'></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{Html.BeginForm("CreateDocument", "MedicalHistory", FormMethod.Get);
    {
        <div>
            <button type="submit" value="Create Document" class="btn-video-play"> <i class='bx bxs-printer'></i>&nbsp;Print</button>

        </div>
    }
    Html.EndForm();
}




<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="MedicalHistory" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="MedicalHistory" asp-action="Index" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                </li>
            }



            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="MedicalHistory" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }

            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="MedicalHistory" asp-action="Index" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="MedicalHistory" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
</div>