ISU By DBugSolutions/Models/EatingSchedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ISU_By_DBugSolutions.Models
{
    public class EatingSchedule
    {
        [Key]
        public int EatingSchedID { get; set; }        
        [Required]
        [Display(Name = "Creche")]
  
        public string CrecheName { get; set; }
        public IEnumerable<Creche> _CrecheName { get; set; }
        
        [Display(Name = "Meal")]
        public string MealName { get; set; }
        public IEnumerable<Meal> _MealName { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Date { get; set; }
    }
}

ISU By DBugSolutions/Controllers/EatingScheduleController.cs
using ISU_By_DBugSolutions.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.Drawing;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Grid;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ISU_By_DBugSolutions.Controllers
{
 
    public class EatingScheduleController : Controller
    {
        private readonly ApplicationDBContext _context;

        public EatingScheduleController(ApplicationDBContext context)
        {
            _context = context;
        }

        public IActionResult Index(int pg = 1, string SearchText = "")
        {
            List<EatingSchedule> enq = _context.EatingSchedule.ToList();
            if (SearchText != "" && SearchText != null)
            {
                enq = _context.EatingSchedule.Where(p => p.CrecheName.Contains(SearchText) || p.MealName.Contains(SearchText) || p.Date.ToString().Contains(SearchText)).ToList();
            }
            else
            {
                enq = _context.EatingSchedule.ToList();
            }

            const int pageSize = 5;
            if (pg < 1)
            {
                pg = 1;
            }
            int recsCount = enq.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = enq.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            return View(data);
        }        

        // GET: Enquiry/Create
        public IActionResult Create()
        {
            List<Creche> listCreche = new List<Creche>();
            listCreche = (from creche in _context.Creche select creche).ToList();
            ViewBag.listCreche = listCreche;
            List<Meal> listMeal = new List<Meal>();
            listMeal = (from meal in _context.Meal select meal).ToList();
            ViewBag.listMeal = listMeal;            
            
            return View();
        }

        // POST: Enquiry/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, ECDC Manager, Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EatingSchedID,CrecheName,MealName,Date")] EatingSchedule eating)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eating);
                await _context.SaveChangesAsync();
                TempData["Message"] = "success";
                return RedirectToAction(nameof(Index));
            }
            return View(eating);
        }
        [Authorize(Roles = "Admin, ECDC Manager")]
        // GET: Enquiry/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            List<Creche> listCreche = new List<Creche>();
            listCreche = (from creche in _context.Creche select creche).ToList();
            ViewBag.listCreche = listCreche;
            List<Meal> listMeal = new List<Meal>();
            listMeal = (from meal in _context.Meal select meal).ToList();
            ViewBag.listMeal = listMeal;

            if (id == null)
            {
                return NotFound();
            }

            var enquiry = await _context.EatingSchedule.FindAsync(id);
            if (enquiry == null)
            {
                return NotFound();
            }
            return View(enquiry);
        }

        // POST: Enquiry/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost] 
        [Authorize(Roles = "Admin, ECDC Manager")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EatingSchedID,CrecheName,MealName,Date")] EatingSchedule eating)
        {
            if (id != eating.EatingSchedID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eating);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnquiryExists(eating.EatingSchedID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eating);
        }
        [Authorize(Roles = "Admin")]
        // GET: Enquiry/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eat = await _context.EatingSchedule
                .FirstOrDefaultAsync(m => m.EatingSchedID == id);
            if (eat == null)
            {
                return NotFound();
            }

            return View(eat);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eatsched = await _context.EatingSchedule
                .FirstOrDefaultAsync(m => m.EatingSchedID == id);
            if (eatsched == null)
            {
                return NotFound();
            }

            return View(eatsched);
        }

        // POST: Enquiry/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enquiry = await _context.EatingSchedule.FindAsync(id);
            _context.EatingSchedule.Remove(enquiry);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnquiryExists(int id)
        {
            return _context.EatingSchedule.Any(e => e.EatingSchedID == id);
        }
        [Authorize(Roles = "Admin,Teacher,ECDC Manager, Regional Coordinator, Provincial Coordinator")]
        public IActionResult CreateDocument()
        {

            PdfDocument doc = new PdfDocument();

            PdfPage page = doc.Pages.Add();

            PdfGrid pdfGrid = new PdfGrid();

            List<EatingSchedule> enq = _context.EatingSchedule.ToList();


            IEnumerable<object> dataTable = enq;

            pdfGrid.DataSource = dataTable;

            PdfGraphics graphics = page.Graphics;


            PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 20);
            PdfFont font1 = new PdfStandardFont(PdfFontFamily.Helvetica, 13);
            graphics.DrawString("Eating Schedule List - Report:", font, PdfBrushes.Black, new PointF(0, 0));
            string date = DateTime.Now.ToString();
            graphics.DrawString(date, font1, PdfBrushes.Black, new PointF(350, 5));
            pdfGrid.Draw(page, new Syncfusion.Drawing.PointF(10, 50));

            MemoryStream stream = new MemoryStream();
            doc.Save(stream);

            stream.Position = 0;

            doc.Close(true);

            string contentType = "application/pdf";

            string fileName = "Report.pdf";

            return File(stream, contentType, fileName);
        }
    }
}

ISU By DBugSolutions/Views/EatingSchedule/Create.cshtml
@model EatingSchedule

@{
    ViewData["Title"] = "Eating Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="mb-3" src="~/Images/meal=schedule-header.png" alt="Creche List" width="300" />

<div class="alert alert-secondary alert-dismissible fade show" role="alert"> Complete form and submit to add eating schedule.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
           
            <div class="form-group">
                <label asp-for="CrecheName" class="control-label"></label>
                <select asp-for="CrecheName" class="form-control" asp-items="@(new SelectList(ViewBag.listCreche,"Name","Name"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="CrecheName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MealName" class="control-label"></label>
                <select asp-for="MealName" class="form-control" asp-items="@(new SelectList(ViewBag.listMeal,"Name","Name"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="MealName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" type="datetime" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index"><img src="~/Images/back-icon.png" alt="back" style="width:35px;" class="mr-1" /></a>
                <input type="submit" value="Confirm" class="btn btn-submit-1" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ISU By DBugSolutions/Views/EatingSchedule/Delete.cshtml
@model EatingSchedule

@{
    ViewData["Title"] = "Eating Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="mb-3" src="~/Images/meal=schedule-header.png" alt="Creche List" width="300" />

<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>Warning!</strong> Deleted records cannot be recovered<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>

<div>
    <h4>Eating Schedule</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CrecheName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CrecheName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MealName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MealName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="EatingSchedID" />
        <a asp-action="Index"><img src="~/Images/back-icon.png" alt="back" style="width:35px;" class="mr-1" /></a>
        <input type="submit" value="Delete" class="btn btn-submit-1" />

    </form>
</div>

ISU By DBugSolutions/Views/EatingSchedule/Details.cshtml
@model EatingSchedule
@{
    ViewData["Title"] = "Eating Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="mb-3" src="~/Images/meal=schedule-header.png" alt="Creche List" width="300" />
<hr />

<div>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CrecheName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CrecheName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MealName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MealName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index"><img src="~/Images/back-icon.png" alt="back" style="width:35px;" class="mr-1" /></a>

</div>

ISU By DBugSolutions/Views/EatingSchedule/Edit.cshtml
@model EatingSchedule
@{
    ViewData["Title"] = "Eating Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img class="mb-3" src="~/Images/meal=schedule-header.png" alt="Creche List" width="300" />

<h4><i>Edit details</i></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EatingSchedID" />
            <div class="form-group">
                <label asp-for="CrecheName" class="control-label"></label>
                <select asp-for="CrecheName" class="form-control" asp-items="@(new SelectList(ViewBag.listCreche,"Name","Name"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="CrecheName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MealName" class="control-label"></label>
                <select asp-for="MealName" class="form-control" asp-items="@(new SelectList(ViewBag.listMeal,"Name","Name"))">
                    <option value="" selected disabled>--Select--</option>
                </select>
                <span asp-validation-for="MealName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index"><img src="~/Images/back-icon.png" alt="back" style="width:35px;" class="mr-1" /></a>
                <input type="submit" value="Save" class="btn btn-submit-1" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ISU By DBugSolutions/Views/EatingSchedule/Index.cshtml
@model IEnumerable<EatingSchedule>

@{
    ViewData["Title"] = "Eating Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";

    Pager pager = new Pager();
    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
    int intSno = 0;
}

<img class="mb-3" src="~/Images/meal=schedule-header.png" alt="Creche List" width="300" />

@if (TempData["Message"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert"> <strong>Success!</strong> Schedule Successfully added.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
}
<p class="h4">
    <a asp-action="Create" class="text-secondary"><i class="bx bxs-plus-square h1 shake"></i><span class="badge badge-secondary h1 bg-anim">Add New</span></a>
</p>
<hr />
<div class="col-4 p-0 justify-content-end">
    <form asp-controller="EatingSchedule" asp-action="Index" class="form-inline">
        <input class="form-control mr-sm-2" type="text" name="SearchText" placeholder="Search..." />
        <button class="btn btn-submit my-2 my-sm-0" type="submit" value="Search">
            Search
        </button>
    </form>
</div>


<table class="table">
    <thead>
        <tr>
        
            <th>
                @Html.DisplayNameFor(model => model.CrecheName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MealName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            intSno = intSno + 1;
            <tr>
          
                <td>
                    @Html.DisplayFor(modelItem => item.CrecheName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MealName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.EatingSchedID" class="text-primary h2"><i class='bx bxs-edit'></i></a>
                    <a asp-action="Details" asp-route-id="@item.EatingSchedID" class="text-secondary h2"><i class='bx bx-list-ul'></i></a>
                    <a asp-action="Delete" asp-route-id="@item.EatingSchedID" class="text-danger h2"><i class='bx bx-trash'></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
@{Html.BeginForm("CreateDocument", "EatingSchedule", FormMethod.Get);
    {
        <div>
            <button type="submit" value="Create Document" class="btn-video-play"> <i class='bx bxs-printer'></i>&nbsp;Print</button>

        </div>
    }
    Html.EndForm();
}
<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="EatingSchedule" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="EatingSchedule" asp-action="Index" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                </li>
            }



            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="EatingSchedule" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }

            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="EatingSchedule" asp-action="Index" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="EatingSchedule" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }


        </ul>
    }
</div>